services:
  - type: web
    name: techshop-api
    runtime: node
    region: oregon
    buildCommand: cd apps/api && npm install --include=dev && npx prisma generate && node build.js
    startCommand: cd apps/api && npx prisma db push && node dist/main.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        value: techshop-secret-key
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
